### ISSUE TITLE
Gloda import and TB versions

### ISSUE THREAD

**Issue by ericdanan** [CamielBouchier/cb_thunderlink#1]
To answer a question you asked in:

https://github.com/mikehardy/thunderlink/issues/64

regarding importing `Gloda` in `cb_api.js`, I looked at the source code and the file `GlodaPublic.jsm` appeared in TB version 74.0b1. Beforehands the file to import is instead `public.js` according to:

https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Creating_a_Gloda_message_query

I see you are instead falling back to importing the file `gloda.js` (I suppose it must be working but just to point this out).

**Comment by CamielBouchier** [comment]
Thanks for finding out. I "correct" the fallback to public.js (which seems to work at least on my 68.12 as well!
