### ISSUE TITLE
File Not Found Error while registerin cb_thunderlink on Ubuntu 20.04

### ISSUE THREAD

**Issue by CaptainPackers** [CamielBouchier/cb_thunderlink#13]
Hi, I'm trying to register cb_thunderlink but getting the following error:

```
$ cd ~/cb_thunderlink
$ ./cb_thunderlink register
Registering ~/cb_thunderlink/cb_thunderlink to Thunderbird (~/.mozilla/native-messaging-hosts/cb_thunderlink.json)
Traceback (most recent call last):
  File "cb_thunderlink.py", line 156, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '~/.mozilla/native-messaging-hosts/cb_thunderlink.json'
[28845] Failed to execute script cb_thunderlink
```

Notes: 

- I have replaced my home directory with '~' in the above output
- my thunderbird installation is in ~/.thunderbird, not ~/.mozilla
- the directory native-messaging-hosts does not exist in either my ~/.mozilla directory or my ~/.thunderbird directory

I am very much interested in using cb_thunderlink links in TiddlyWiki, which is an integral part of my workflow, and would appreciate any guidance you can provide to get the OS integration working.

Thanks in advance.

CaptainPackers

**Comment by CaptainPackers** [comment]
I created the directory native-messaging-hosts in ~/.mozilla and copied cb_thunderlink.json there from ~/cb_thudnderlink, and was then able to register the OS integration app. I then removed and reinstalled the cb_thunderlink extension, per the readme instructions, but the direct link OS integration does not work, it does not switch to thunderbird and it does not open the email when I click on the link in a tiddlywiki tiddler. The copy and paste alternative works, but it is not as convenient.

**Comment by CamielBouchier** [comment]
@CaptainPackers 

* It is OK that the `native-messaging-hosts` is under `.mozilla`. That seems to be the way it works for native messaging.
* There was indeed an issue that the directory was not created if it did not exist. Fixed that.
* I would be careful with copying around. The json file is created through the register command and has a self-reference to the executable. 
* Can you share, after you did all from scratch again:
** The contents of the `cb_thunderlink.json` under `.mozilla/native-messaging-hosts`?
** The output created by the command `cb_thunderlink register`?
** The output that appears in the development console of thunderbird?
** The linux system you are using? Maybe I can reproduce better in that case.

By the way, I am also using this in connection with TiddlyWiki, allbeit under Windows. Did make a trial under XUbuntu 18.04 and there it works as well.

Camiel B.

**Comment by CaptainPackers** [comment]
Camiel,

I removed native-messaging-hosts from under .mozilla and did a complete uninstall and reinstall using the update above. Here is the output of the register command:

```
$ ./cb_thunderlink register
Registering ~/cb_thunderlink/cb_thunderlink to Thunderbird (~/.mozilla/native-messaging-hosts/cb_thunderlink.json)
Writing ~/.local/share/applications/cb_thunderlink_cbthunderlink.desktop
Executing ['gio', 'mime', 'x-scheme-handler/cbthunderlink', 'cb_thunderlink_cbthunderlink.desktop']
(b'Set cb_thunderlink_cbthunderlink.desktop as the default for x-scheme-handler/cbthunderlink\n', None)
Writing ~/.local/share/applications/cb_thunderlink_thunderlink.desktop
Executing ['gio', 'mime', 'x-scheme-handler/thunderlink', 'cb_thunderlink_thunderlink.desktop']
(b'Set cb_thunderlink_thunderlink.desktop as the default for x-scheme-handler/thunderlink\n', None)
```

I have replaced references to my home directory in the output with ~.
Now a new browser tab opens with 

cbthunderlink//MjAyMC0xMS0xOFQxNTo0MjoxMC4wMDBaO0VNVSBJUklNIDx4emhvdTJAZW1pY2guZWR1Pg==

in the address bar and a site can't be reached message.

I don't know how to run the development console in thunderbird.

Regards,
CaptainPackers

**Comment by CamielBouchier** [comment]
@CaptainPackers ,

I see no obvious problem. Assuming that the missing ':' in 'cbthunderlink' is a typo.

Any chance your thunderbird is installed through snap? I learned meanwhile that is a problem (and not one I can fix).

The directory where your cb_thunderlink is installed also contains a log directory and log files. Can you share?

Camiel B.

**Comment by CaptainPackers** [comment]
Camiel,

Not a typo. The ':' is in the link text in the two apps I'm testing in, Wekan, which is a snap install, but also in TiddlyWiki. In Wekan, clicking on the link opens a browser window or tab and drops the link text in without the ':'

TiddlyWiki assumes it is a reference to a non-existing tiddler. I am running TiddlyWiki in TiddlyDesktop.

Is there a way to send you the log file and keep it private?

Thanks,
CaptainPackers

**Comment by CamielBouchier** [comment]
@CaptainPackers,

I am pretty confused by your explanation.
A link should have the format `thunderlink://` or `cb_thunderlink://`. 
I just did a code review and if not there wouldn't be any response indeed.
(so clicking a link should pass something in above format to the executable).

You can send logs to c a m i e l @ b o u c h i e r . b e , but I am pretty sure they just would confirm above. Unless I misunderstood you ...

Camiel B.

**Comment by CamielBouchier** [comment]
Please follow the [checklist](https://camiel.bouchier.be/en/cb_thunderlink/checklist) I drafted. That will enable me to answer better what the problem is.
