### ISSUE TITLE
I have very similar problem but with cb_thunderlink.exe. (Windows)

### ISSUE THREAD

**Issue by CamielBouchier** [CamielBouchier/cb_thunderlink#14]
I have very similar problem but with cb_thunderlink.exe. 
`C:\thunderlink\cb_thunderlink>C:\thunderlink\cb_thunderlink\cb_thunderlink.exe "thunderlink://messageid=ee0c03d5162447cbb035c93ebdc8c422@Ex2.example.pl"
Traceback (most recent call last):
  File "cb_thunderlink.py", line 202, in <module>
ConnectionRefusedError: [WinError 10061] Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia
[11616] Failed to execute script cb_thunderlink`

I'm using
- Thunderbird 78.4.3;
- cb_thunderlink 0.6.

_Originally posted by @RadoslawKokoc in https://github.com/CamielBouchier/cb_thunderlink/issues/11#issuecomment-726856041_

**Comment by CamielBouchier** [comment]
@RadoslawKokoc,

I do not exactly understand.
What are you exactly trying to do? Is this in the registration step where I would expect `cb_thunderlink.exe register`? Or where and when is this output exactly generated?

Camiel B

**Comment by RadoslawKokoc** [comment]
> What are you exactly trying to do? 
I'll try to explain.

Is this in the registration step where I would expect `cb_thunderlink.exe register`? 
I tried to open a link "thunderlink://messageid=ee0c03d5162447cbb035c93ebdc8c422@Ex2.example.pl" in Thunderbird installed on my PC.

Or where and when is this output exactly generated?
The output was generated during execution of cb_thunderlink.exe with the mentioned above link in cmd window.
rk

**Comment by CamielBouchier** [comment]
@RadoslawKokoc 

Cannot reproduce. Does work at my end.

Did you:
1. Install in thunderbird the xpi extension?
2. Register using `cd C:\thunderlink\cb_thunderlink` and issue from there `cb_thunderlink.exe register`?
3. Have thunderbird up and running when executing subsequently the command?

Camiel B.

**Comment by RadoslawKokoc** [comment]
> * Install in thunderbird the xpi extension?
Yes.
> * Register using `cd C:\thunderlink\cb_thunderlink` and issue from there `cb_thunderlink.exe register`?
Yes.
> * Have thunderbird up and running when executing subsequently the command?
No. I've assumed that cb_thunderlink.exe do it for me (make Thunderbird up and running). 
rk

**Comment by CamielBouchier** [comment]
@RadoslawKokoc ,

No, that auto-start functionality is lost (the new thunderbird interface does not support passing parameters trough the command line, that was one of the issues). I *guess* that implementing it through the cb_thunderlink.exe might be possible, but it would be such a mess over the different OS'es that it doesn't pay-off against simply have it running ...

Camiel B.
