### ISSUE TITLE
Registering system integration fails with: `GLIBC_2.29' not found`

### ISSUE THREAD

**Issue by vlcinsky** [CamielBouchier/cb_thunderlink#18]
OS: Debian 10 Buster

```shell
$ ./cb_thunderlink register
[23303] Error loading Python lib '/home/javl/install/cb_thunderlink/cb_thunderlink/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/javl/install/cb
_thunderlink/cb_thunderlink/libpython3.8.so.1.0)
```

There seem to be similar issues with other tools, such as https://github.com/deltachat/deltachat-desktop/issues/1006

It is proposing to install lib6 from testing but it would be nicer to keep using standard system version, if possible.

I did not test the fix using installation from testing (yet)

**Comment by CamielBouchier** [comment]
Let me propose an alternative.

Actually, `cb_thunderlink` is a self-extracting python script, along with the interpreter and all dependencies needed.
Apparently my packaging expects a GLIBC that you don't have.

But you could as well grab the source from github, dump it in some directory and run `cb_thunderlink.py` with a reasonable recent python3 interpreter. Should work equally well and probably less intrusive on your system.

Camiel B.

**Comment by vlcinsky** [comment]
Thanks for the proposal. I will try (it may take some days, but cb_thunderlink stuff is of high importance to me)

**Comment by CamielBouchier** [comment]
@vlcinsky ,

I just realize you might need to extend the script with a `shebang` line (https://stackoverflow.com/questions/7670303/purpose-of-usr-bin-python3) in order to work just like that.

When  you report back this approach works I will add it at my end as well and document the approach. 

Camiel B.
