### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ericdanan** [CamielBouchier/cb_thunderlink#2]
I suppose the add-on doesn't need all the permission that are listed in `manifest.json`. Do you have ideas on which ones are really needed? Would you like me to experiment removing some and checking if things still work?

**Comment by CamielBouchier** [comment]
@ericdanan : yes, I kept all open to avoid issues related to permissions. I would appreciate you checking and clarifying indeed. Do not forget that ultimately I will have also a script launched. Something like 'nativeMessaging'  for sure must stay as well.
