### ISSUE TITLE
Thunderbird Version 78

### ISSUE THREAD

**Issue by 73** [CamielBouchier/cb_thunderlink#20]
Hey,
I am on TB v78 already. Are there any plans to provide support for v78 as well?

Thanks.

**Comment by CamielBouchier** [comment]
I am on 78. And it works. Is it that you want to know before trying or did your trying fail?

Camiel B.

**Comment by 73** [comment]
Hi Camiel,

thanks for getting back to me. I confused the install section with the former thunderlinks.

Sorry for the fuzz!

**Comment by kgorlen** [comment]
cb_thunderlinks work with 78.5.0, but not the old thunderlinks -- is that expected?

**Comment by CamielBouchier** [comment]
No, I expect it to work with previous thunderlinks. And at my end it does.

Op 2020-11-25 om 23:41 schreef kgorlen:
