### ISSUE TITLE
Change commands shortcuts

### ISSUE THREAD

**Issue by e3rd** [CamielBouchier/cb_thunderlink#21]
Amazing, thanks a lot, saved my day!

I don't see a menu option to get the link from within the message. No problem, I prefer to use a shortcut. I've found in the source code the shortcuts like `Ctrl+Alt+1` launching commands like `copy_link_1`. Cool, nice work! Is there any possibility to change the shortcuts? I don't see such menu in preferences. Or at least, how I can invoke a registered command from within the developer tools? `goDoCommand("copy_link_1")` does nothing. (I'm using [`tbkeys`](https://github.com/wshanks/tbkeys) so I prefer the most to set shortcuts this way.)

**Comment by e3rd** [comment]
I get it! Great!

![image](https://user-images.githubusercontent.com/6942231/100114942-3e38ee80-2e72-11eb-9134-c9e39602de58.png)


However, would you advice me how to invoke a registered command from within the developer tools? Thanks!

**Comment by CamielBouchier** [comment]
> I don't see a menu option to get the link from within the message.

In the window where all messages of a folder are displayed, you can select one and right-mouse should give the context-menu to create the link.

Camiel B.
