### ISSUE TITLE
not pasting when using the cb_thunderlink icon?

### ISSUE THREAD

**Issue by JotaPin** [CamielBouchier/cb_thunderlink#24]
Dear all,
When copying the link from (e.g. org-mode) and pressing the icon in TB, it does nothing.
From what I understood, pressing the icon should paste the link in TB?
(using TB78.5.0 under windows)
Best regards,
JotaPin

**Comment by CamielBouchier** [comment]
@JotaPin ,

Can you first run this checklist : https://camiel.bouchier.be/en/cb_thunderlink/checklist ?
Let me know where you get stuck or need more clarification.

Camiel B.

**Comment by jschaeff** [comment]
Hi, I have the same issue in Archlinux, Thunderbird 78.6.0. Nothing happens when clicking th cb_thunderlink button.

I went through the checklist, here is the consoleJS output;

Test generating a cbthunderlink and clicking on the cb_thunderlink button:

```
handle_incoming_link cbthunderlink://MjAyMS0wMS0wNVQwNzo1Mzo1NS4wMDBaO0FHQVRFIDxhZ2F0ZUBjbnJzLmZyPg== cb_background.js:231:13
Investigate me. the_message == null. ml: 
Object { id: null, messages: [] }
cb_background.js:272:21
    handle_incoming_link moz-extension://557e7149-cb90-4a87-998f-d513c3299b67/cb_background.js:272
```

Test generating a thunderlink and clicking on the cb_thunderlink button (sorry about the ugly format, I was not able to export the log console):

```
handle_incoming_link thunderlink://messageid=20210105075355.BCB49808E@tcgpphp53gt.dsi.cnrs.fr cb_background.js:231:13
WebExtensions: cb_show_message_from_msg_id 20210105075355.BCB49808E@tcgpphp53gt.dsi.cnrs.fr three_pane 
Array []
 
Array []
cb_api.js:66
WebExtensions: Investigate me. the_message == null. collection: 
{…}
​
_idMap: Object {  }
​
_listener: Object { onItemsAdded: onItemsAdded(), onItemsModified: onItemsModified(), onItemsRemoved: onItemsRemoved(), … }
​
_nounDef: Object { name: "message", allowsArbitraryAttrs: true, isPrimitive: false, … }
​
deferredCount: -1
​
inverseReferencesByNounID: Object { 102: {} }
​
items: Array []
​
masterCollection: Object { _nounDef: {…}, deferredCount: -1, resolvedCount: 1, … }
​
query: Object { options: {}, _limit: 0, completed: true, … }
​
referencesByNounID: Object { 102: {} }
​
resolvedCount: 1
​
subCollections: Object {  }
​
<prototype>: {…}
​​
_onItemsAdded: function _onItemsAdded()
​​
_onItemsModified: function _onItemsModified()
​​
_onItemsRemoved: function _onItemsRemoved()
​​
_onQueryCompleted: function _onQueryCompleted()
​​
becomeExplicit: function becomeExplicit()
​​
clear: function clear()
​​
listener: 
​​
<get listener()>: listener()
​​​
length: 0
​​​
name: "get listener"
​​​
<prototype>: function ()
​​
<set listener()>: listener()
​​​
length: 1
​​​
name: "set listener"
​​​
<prototype>: function ()
​​
<prototype>: {…}
​​​
__defineGetter__: function __defineGetter__()
​​​
__defineSetter__: function __defineSetter__()
​​​
__lookupGetter__: function __lookupGetter__()
​​​
__lookupSetter__: function __lookupSetter__()
​​​
__proto__: 
​​​
constructor: function Object()
​​​
hasOwnProperty: function hasOwnProperty()
​​​
isPrototypeOf: function isPrototypeOf()
​​​
propertyIsEnumerable: function propertyIsEnumerable()
​​​
toLocaleString: function toLocaleString()
​​​
toSource: function toSource()
​​​
toString: function toString()
​​​
valueOf: function valueOf()
​​​
<get __proto__()>: function __proto__()
​​​
<set __proto__()>: function __proto__()
cb_api.js:102

​```

**Comment by CamielBouchier** [comment]
Did you follow the checklist also on those ? :

> Is global indexing enabled?
> 
>     Can you actually find the message through the 'search messages' option of thunderbird itself? Try locating it with author and date.
>     One of the options of thunderbird is 'global indexing'. Go to the thunderbird generic options (location might be different with different versions) and make sure the 'global indexing' checkbox is checked. If not, searching probably won't work at all.
>     Restart thunderbird and try again.
> 
> Rebuild global-messages-db.sqlite
> 
> If above did not work :
> 
>     Close thunderbird, go to the profile directory and remove global-messages-db.sqlite
>     Reopen thunderbird and wait until global-messages-db.sqlite is rebuild (i.e. you do not see changing it anymore). Depending on your setup that can take quite some time.
>     Try again.

You *did* rebuild the database? You *did* enable global indexing? You *are* able finding the message by author and date through the standard thunderbird search functionality?

Camiel B.

**Comment by jschaeff** [comment]
Thank you for your fast response.
Maybe thunderbird was still rebuilding it's database when I did the tests (I removed the sqlite file and waited a while, maybe not enough).
Now, it seems to work for the classicals thunderlink (I click the cb_thunderlink button and it jumps to the email corresponding to the thunderlink:// url)

With a cbthunderlink:// it does not work. Console cries about :+1: 

```
Investigate me. the_message == null. ml: 
Object { id: null, messages: [] }
cb_background.js:272:21
    handle_incoming_link moz-extension://557e7149-cb90-4a87-998f-d513c3299b67/cb_background.js:272

```

**Comment by CamielBouchier** [comment]
Hmz. That is puzzling.

Also if you search for that message on the basis of author and date, using the standard thunderbird search panel, are you able locating it?

Camiel B.

**Comment by jschaeff** [comment]
This morning, cbthunderlnk works also. Thank you for your help and for your project ! I was realy missing the thunderlink extension.

**Comment by CamielBouchier** [comment]
Great news and you're welcome.

I suspect lots of times this issue is related to a corrupted sqlite database. And it is not related to the plugin but to the core functionality of thunderbird. I think up to now it always reflected into not being able finding the message ' the manual way ' neither.

Camiel B.
