### ISSUE TITLE
Can't open thunderlink/cb_thunderlink links

### ISSUE THREAD

**Issue by novoid** [CamielBouchier/cb_thunderlink#29]
Hi,

Xubuntu 20.04.02 LTS, cb_thunderlink 0.8.0, Thunderbird 78.7.1

Registered cb_thunderlink:

```
vk@host ~/cb_thunderlink % ./cb_thunderlink register
Registering /home/vk/cb_thunderlink/cb_thunderlink to Thunderbird (/home/vk/.mozilla/native-messaging-hosts/cb_thunderlink.json)
Writing /home/vk/.local/share/applications/cb_thunderlink_cbthunderlink.desktop
Executing ['gio', 'mime', 'x-scheme-handler/cbthunderlink', 'cb_thunderlink_cbthunderlink.desktop']
(b'Set cb_thunderlink_cbthunderlink.desktop as the default for x-scheme-handler/cbthunderlink\n', None)
Writing /home/vk/.local/share/applications/cb_thunderlink_thunderlink.desktop
Executing ['gio', 'mime', 'x-scheme-handler/thunderlink', 'cb_thunderlink_thunderlink.desktop']
(b'Set cb_thunderlink_thunderlink.desktop as the default for x-scheme-handler/thunderlink\n', None)
vk@host ~/cb_thunderlink %
```

I can generate thunderlinks (and adapted for org). However, I can not open any link. When trying to follow a link, Thunderbird is brought to foreground + focus but no email is shown. (Indexer is enabled - as I've learned in another issue here.)

Here are example lines:
```
vk@host ~/cb_thunderlink % /usr/bin/thunderbird -thunderlink thunderlink://messageid=520169809b1f43448c7d17d792db4b11@example.com
vk@host ~/cb_thunderlink % /usr/bin/thunderbird -thunderlink cbthunderlink://MjAyMS0wMi0yNVQxM...XlAem50LmRlPg==
vk@host ~/cb_thunderlink % ./cb_thunderlink cbthunderlink://MjAyMS0wMi0yNVQxM...XlAem50LmRlPg== 
vk@host ~/cb_thunderlink % ./cb_thunderlink thunderlink://messageid=520169809b1f43448c7d17d792db4b11@example.com
vk@host ~/cb_thunderlink %
```
Each of them is switching to TB but not showing the message I'm querying for.

What can I check?

Thanks for your time!

**Comment by CamielBouchier** [comment]
Hi,

Can I suggest you first run carefully through:  https://camiel.bouchier.be/en/cb_thunderlink/checklist ?
If it doesn't solve your problem, I have at least the necessary information to have a deeper look.

(and if the checklist would not be clear, feel free to drop me a note).

Camiel B.

**Comment by CamielBouchier** [comment]
BTW, you might have as well a look to https://camiel.bouchier.be/en/cb_thunderlink/architecture.
I notice you are trying `thunderbird -thunderlink` but that most certainly will not work.
You should use the `cb_thunderlink` variant (which is actually a python script packaged along with the interpreter).

Camiel B.

**Comment by CamielBouchier** [comment]
And a BTW on the BTW ;)
My first guess is that you are on a snap installation of thunderbird. Won't work ... As documented in the checklist.

Camiel B.

**Comment by novoid** [comment]
Wow, what a great checklist! You should make it more prominent in your README.

Installation: check.

Basic functionality: check.

OS integration: no snap on my machine - on purpose ;-) -> check.

My test runs:
```
vk@host ~/cb_thunderlink % ./cb_thunderlink thunderlink://messageid=520169809b1f43448c7d17d79xxxxxx@example.com                             
vk@host ~/cb_thunderlink % ./cb_thunderlink thunderlink://messageid=81b52275-5ad2-1970-ab6c-2735xxxxxxx@example.com
```
In the Console, I get:
```
handle_incoming_link thunderlink://messageid=81b52275-5ad2-1970-ab6c-2735exxxxxxx@example.com cb_background.js:231:13

WebExtensions: cb_show_message_from_msg_id 81b52275-5ad2-1970-ab6c-2735ef29605f@RISE-world.com three_pane 
[...details omitted...]

NS_ERROR_NOT_AVAILABLE: PreferDisplayName: undefined - not a boolean 4 AddrBookCard.jsm:197
    getPropertyAsBool resource:///modules/AddrBookCard.jsm:197
```

From my limited knowledge, I tend to think that this is an error message you can work with.

Please tell me when I should investigate anything any further or provide more details.

Your time is very much appreciated - thanks!

**Comment by CamielBouchier** [comment]
Thanks for your feedback and having run the checklist. Now we can get serious ;)
Can you do one more test for me? If you use *exactly* the same link through the cb_thunderlink button, all goes fine?
Thàt would be puzzling ...

Camiel B.

**Comment by novoid** [comment]
Command:
```
./cb_thunderlink cbthunderlink://MjAyMS0wMy0wMVQxOTo1MzoyMC4wMDBaO0thcmwgVm9pdCA8S2FybC5Wb2l0QFJJU0Utd29ybGQuY29tPg==
```

Here is the output:
```
Investigate me. the_message == null. ml: 
Object { id: null, messages: [] }
cb_background.js:272:21
    handle_incoming_link moz-extension://8adf1afe-3fc0-4f0d-a40a-f3d7a5b197bb/cb_background.js:272
```

**Comment by CamielBouchier** [comment]
No, no, this is not what I meant. I was wondering if the link `thunderlink://messageid=81b52275-5ad2-1970-ab6c-2735exxxxxxx@example.com` (which you probably obfuscated, but that is not the issue) works by pasting using the button provided therefore in thunderbird. (so not through the script, but through the button). I confused you probably with the cb_ part ;)

Camiel B.

**Comment by novoid** [comment]
Ah, you just explained me a feature I was not aware of yet.

The thunderlink-URL works, the cb_thunderlink-URL doesn't work when being in the clipboard while pushing the button.

**Comment by CamielBouchier** [comment]
Well, don't trust too much on that response time. I just happen to be fiddling around on an other project ;)

But let's try to zoom in and concentrate only on the `thunderlink://...` part.
* You pick up a message via the `thunderlink` context menu. So you have a `thunderlink://..` in your clipboard.
* When you paste using the button it works.
* When you apply that very same `thunderlink://..` through the script `./cb_thunderlink thunderlink://...` you got that message referring to 'AddrBookCard.jsm'. Correct?
* Is it just for some messages or for all?

If you look to the architecture document the button and the script are just alternative ways of dropping the link in the machinery. So I am puzzled that the one would work and the other not ... Something doesn't rhyme yet ...

Camiel B.

**Comment by novoid** [comment]
I rebooted my system (which I usually don't) - just in case.

I restarted TB and modified my Org config to use the Python script instead of the thunderbird executable:

```
  ;; modify this for your system
  (setq thunderlink-program "/home/vk/cb_thunderlink/cb_thunderlink")

  (defun my-open-message-id-in-thunderbird (message-id)
  "open an email with a given message-ID in Thunderbird"
  (interactive)
  (start-process
   (concat "thunderlink: " message-id)
   nil
   thunderlink-program
   (concat "thunderlink://messageid=" message-id)
   )
  )

  (defun org-message-thunderlink-open (slash-message-id)
    "Handler for org-link-set-parameters that converts a standard message:// link into
   a thunderlink and then invokes thunderbird."
    ;; remove any / at the start of slash-message-id to create real message-id
    (let ((message-id
           (replace-regexp-in-string (rx bos (* ":"))
                                     ""
                                     slash-message-id)))
      (my-open-message-id-in-thunderbird message-id)
  ))

  (org-link-set-parameters "messageid" :follow #'org-message-thunderlink-open)
```

**This is now working!**

I don't know why the previous behavior was somehow working but not completely. I'm sorry for having wasted your time.

FYI: I'm thinking of adding cb_thunderlink to the whole thing just to be sure. This way, I would not get `[[<link>][<time> <sender> <subject>]]` but an extended combination of `[[<link>][<time> <sender> <subject>]] [[<cb_link>][cb]]` instead which gives me two separate links to be on the safe side, in case the first one gets broken some day.

**Comment by CamielBouchier** [comment]
You're welcome.

But in any case, as I tried to explain in the beginning and in the documentation `thunderBIRD blahblah` won't work. For sure. You really need the `thunderlink blahblah` as entry point for system integration. But glad it works.

On a different note, based on your question and your profile I learned you are an org-mode afficionado. What makes it so great? I am *very* attached to tiddlywiki (*) and always interested in a comparison ...

Camiel B.

(*) A priori we agree a good system should be open and text based ...

**Comment by novoid** [comment]
> On a different note, based on your question and your profile I learned you are an org-mode afficionado. What makes it so great? I am _very_ attached to tiddlywiki (*) and always interested in a comparison ...

I tried to summarize some points on https://karl-voit.at/orgmode/
In combination with Emacs it's so much more than just [syntax](https://karl-voit.at/2017/09/23/orgmode-as-markup-only/).

Org is a completely different universe from my point of perspective. If you're interested in the big picture, you might enjoy https://karl-voit.at/2017/02/10/evolution-of-systems/

In short: Org seems to be inferior to anything I've come across so far in the PIM domain. If you're not familiar with the Emacs - don't worry. There are tons of people out there who report that learning Emacs just for Org was worth the effort big time.
