### ISSUE TITLE
cbthunderlink link is not working in 78.8.1

### ISSUE THREAD

**Issue by tekvsakdan** [CamielBouchier/cb_thunderlink#32]
Thunderbird 78.8.1

Issue:
- thunderlink is working
- cbthunderlink is not working

Cbthunderlink link doesn't work if a sender has hypen in the e-mail address. The commit c12c92d377bef5a72d32818707c91375f24c59ad doesn't solve the issue anymore.

**Comment by CamielBouchier** [comment]
Is this still somehow relevant? If not I will close "soon".

Camiel B.

**Comment by tekvsakdan** [comment]
This is still an issue. cbthunderlink links doesn't work on some messages, on the other side thunderlink links works perfectly. I also install 1.4.0 version and the symptoms are the same.

I suspect it has something with the letter "-" inside e-mail address. For example, cbthunderlink doesn't work if mail was sent from no-reply@mail.goodreads.com, and it works fine if it is sent from ak@ultramaraton.si.

**Comment by CamielBouchier** [comment]
Hi,

Normally I don't use cbthunderlink. So I did check and investigate some deeper on my installation.
Initially it didn't work at all for an address containing "-". It appears that the substitution of '-' in my code was the culprit.
So I changed code back as follows:

```
 if (link_type == 'cbthunderlink') {
        let decoded_link = atou(link)
        let date_auth = decoded_link.split(";")
        let the_date = new Date(date_auth[0])
        // See issue #10 for the replace.
        let the_author = date_auth[1]
        // CB XXX and out again: let the_author = date_auth[1].replace(/-/g, '')
        let the_query = {
            author   : the_author,
            fromDate : the_date,
            toDate   : the_date
        }
```

After that, it works at least again at my end.
The replacement was strange in the first place ...

Can you reproduce this at your end, rebuild and carefully analyze if there's still an issue and what it might be?

Camiel B.

**Comment by tekvsakdan** [comment]
Now it works as expected :)

The issue with the "-" was in Thunderbird (database) before version 78. It looks like they fixed that.

**Comment by CamielBouchier** [comment]
Thanks for the feedback.
Just to be sure: "now it works" means the code as above in which '-' is not replaced by ''?
(and which is the one that works at my end as well)
Camiel B.

**Comment by tekvsakdan** [comment]
Yes, without "-" replacement works as expected.

**Comment by CamielBouchier** [comment]
Closed. Solved in https://github.com/CamielBouchier/cb_thunderlink/releases/tag/Release_1_5_0
