### ISSUE TITLE
Thunderlinks for some email messages not copied to clipboard

### ISSUE THREAD

**Issue by kgorlen** [CamielBouchier/cb_thunderlink#34]
Thunderbird 91.4.0 (64-bit) with cb_thunderlink 0.8 for Windows (but the Version shown in the add-on is 0.6.0)

Here's an example: I have two messages in my inbox:

![image](https://user-images.githubusercontent.com/17185483/145747242-39e9a881-24cc-42a5-8617-f5d11a3f3093.png)

Creating a thunderlink for the second message copies a working link to the clipboard:

Fwd: Risks of not getting booster | Newsom going after gun makers | Harris unfazed by headlines | e-Edition thunderlink://messageid=1864133460.24330.1639325282432@connect.xfinity.com

But creating a thunderlink for the first message leaves the clipboard unchanged.

Heres the header of the failing message:

Return-Path: <ccweisner@comcast.net>
Delivered-To: gorlen@comcast.net
Received: from dovdir4-hob-04o.email.comcast.net ([96.102.179.230])
	by dovback4-hob-24o.email.comcast.net with LMTP
	id 6K1yC9hbtmGbSAAAD/ALhw
	(envelope-from <ccweisner@comcast.net>)
	for <gorlen@comcast.net>; Sun, 12 Dec 2021 20:30:16 +0000
Received: from dovpxy-asa-10o.email.comcast.net ([96.102.179.230])
	by dovdir4-hob-04o.email.comcast.net with LMTP
	id AEMbC9hbtmG2KwAALnO4HA
	(envelope-from <ccweisner@comcast.net>)
	for <gorlen@comcast.net>; Sun, 12 Dec 2021 20:30:16 +0000
Received: from reszmta-h1p-037921.sys.comcast.net ([96.102.179.230])
	by dovpxy-asa-10o.email.comcast.net with LMTP
	id EKxcKNdbtmE5fAAAcsybWg
	(envelope-from <ccweisner@comcast.net>)
	for <gorlen@comcast.net>; Sun, 12 Dec 2021 20:30:15 +0000
Received: from resomta-po-02v.sys.comcast.net ([96.114.154.226])
	by reszmta-h1p-037921.sys.comcast.net with ESMTP
	id wV7zmRTu9aV1awVU7mJENf; Sun, 12 Dec 2021 20:30:15 +0000
Received: from [IPv6:::ffff:192.168.1.156] ([24.23.174.254])
	by resomta-po-02v.sys.comcast.net with ESMTPSA
	id wVU4mva884iGOwVU4mtSQ4; Sun, 12 Dec 2021 20:30:15 +0000
X-CAA-SPAM: F00000
X-Xfinity-VAAS: gggruggvucftvghtrhhoucdtuddrgedvuddrkeeigddugedtucetufdoteggodetrfdotffvucfrrhhofhhilhgvmecuvehomhgtrghsthdqtfgvshhipdfqfgfvpdfpqffurfetoffkrfenuceurghilhhouhhtmecufedtudenucgopfhokfffucdluddtmdenucfjughrpeggvffhufffkgfrjghftgesmhdttdertddtjeenucfhrhhomhepvegrrhholhcuhggvihhsnhgvrhcuoegttgifvghishhnvghrsegtohhmtggrshhtrdhnvghtqeenucggtffrrghtthgvrhhnpeffhfdvteeflefgjeefudfhueffhfethfdvuddvgfdufeeugfelheevtdduueetveenucffohhmrghinheprhhhnhhsfhdrohhrghenucfkphepvdegrddvfedrudejgedrvdehgeenucevlhhushhtvghrufhiiigvpedtnecurfgrrhgrmhephhgvlhhopeglkffrvheimeemmehffhhffhemudelvddrudeikedruddrudehiegnpdhinhgvthepvdegrddvfedrudejgedrvdehgedpmhgrihhlfhhrohhmpegttgifvghishhnvghrsegtohhmtggrshhtrdhnvghtpdhrtghpthhtohepghhorhhlvghnsegtohhmtggrshhtrdhnvght
X-Xfinity-VMeta: sc=10.00;st=legit
MIME-Version: 1.0
To: Keith <gorlen@comcast.net>
From: Carol Weisner <ccweisner@comcast.net>
Subject: RE: quicken report on charitable donations for 2021
Date: Sun, 12 Dec 2021 12:30:14 -0800
Importance: normal
X-Priority: 3
In-Reply-To: <51d8d6e7-4fad-812a-b2d5-c9a6312ed7d6@comcast.net>
References: <51d8d6e7-4fad-812a-b2d5-c9a6312ed7d6@comcast.net>
Content-Type: multipart/mixed;
	boundary="_2B014044-3145-499D-8C99-7598B53FBC62_"

--_2B014044-3145-499D-8C99-7598B53FBC62_
Content-Type: multipart/alternative;
	boundary="_1551273C-E70F-4093-BDEB-4CCE953138BD_"

--_1551273C-E70F-4093-BDEB-4CCE953138BD_
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"

**Comment by CamielBouchier** [comment]
Hi,

This is hard to debug.

I did write in the past some kind of detailed checklist: https://camiel.bouchier.be/en/cb_thunderlink/checklist

Can you run carefully through that one in order to understand better where the issue might be?

Camiel B.

**Comment by kgorlen** [comment]
The symptoms have changed.  A thunderlink for this message is now copied to the clipboard, and it does open the message, unless it's in the Trash folder -- most of the time.  It seems that the problem is related to global-messages-db.sqlite, which I did not rebuild.

**Comment by CamielBouchier** [comment]
I will consider closed.
Camiel B.
