### ISSUE TITLE
Add shortcut

### ISSUE THREAD

**Issue by henningninneh** [CamielBouchier/cb_thunderlink#37]
Hi,

I love this add-on, and I would love it even more if, instead of having to click the thunderlink button, I could just press a combination of keys (a shortcut) to open a message. I use my mouse very little and a have minimalist thunderbird layout without any buttons and toolbars. A shortcut like ctrl-t (or configurable) would make the workflow simpler.

Thanks a lot!
Henning

**Comment by CamielBouchier** [comment]
Hi,
Makes sense. I implemented. Default combination is Ctrl+Alt+0 (to align with the Ctrl+Alt+1 ... for creating the link).
Camiel B.

**Comment by henningninneh** [comment]
Fantastic, thanks!
