### ISSUE TITLE
FR: keyboard shortcut

### ISSUE THREAD

**Issue by sevehub** [CamielBouchier/cb_thunderlink#39]
Would it be possible to have a keyboard shortcut that calls the function  __handle_incoming_link__  in the same way that the button in the UI does?

**Comment by sevehub** [comment]
Sorry, already exists, CTRL-ALT-0.

**Comment by CamielBouchier** [comment]
Indeed. Exists already, but not that long yet.
As a note: the CTRL-ALT-0 is the "default" key combination. 
You can change it.
Camiel B.

**Comment by sevehub** [comment]
Thanks, Camiel,
I've recently written about how I use your extension with VIM [on my blog](https://tinyurl.com/y98cnkxu). Your comments would be greatly appreciated.
Regards,
S
