### ISSUE TITLE
Avoid ugly CMD window pop-up

### ISSUE THREAD

**Issue by lucker999** [CamielBouchier/cb_thunderlink#40]
Hello Camiel,

thank you for reviving the very handy extension, I appreciate it!

Could you please add some parameters to the .exe file to avoid this ugly CMD window popping up each time I click on CB_thunderlink? I know how to make it in a .bat file, but have no clue how to edit the .exe.

It would be also awesome to have this wonderful app in [chocolatey](https://community.chocolatey.org/packages) as a package to update it easily.

**Comment by CamielBouchier** [comment]
Hi,
The balance between "how much it annoys" and "how much time do I have" is still in favor of "accept the brief pop-up".
I did look earlier to it, and it's a bigger can of worms then you would imagine (certainly if to be maintained over Windows and Linux).

Now, if you want to experiment: the exe file is actually only a packaging of the python files you will find in the source. So if you take the python files, install a python interpreter, you can start playing with it ...

And yes, it would be wonderful to have it in eleven-thirty distributions ... but again, my time is limited. As long as I can click my thunderlinks and they navigate to the right mail, I am happy. I implemented that part to keep thunderlink surviving, I implemented that part reasonably well maintainable, and it's the part I am going to focus on. But again ... feel free.

Will not close the request. Someone, e.g. my future self, might want to have a look into it.

Camiel B.

**Comment by CamielBouchier** [comment]
@lucker999: I was now looking with fresh eyes into this and maybe it is easier than I anticipated after all. Seems to have it on Windows, but was wondering if you could test in Linux?

Camiel B.

**Comment by CamielBouchier** [comment]
Unlike told 2 weeks ago: I need to keep this ugly command window (e.g. for the registration part). I could split in two different scripts, one packaged with a command window, and one without. But it complicates maintenance far beyond the minor annoyance of the brief pop-up window. Closing definitively.

Camiel B.
