### ISSUE TITLE
Releases do not contain the latest xpi file

### ISSUE THREAD

**Issue by BenjaminKobjolke** [CamielBouchier/cb_thunderlink#41]
On your website you state "Head to the latest release and download the cb_thunderlink.xpi from the assets. ".
But I can't find the xpi within the last few releases. Did you miss to add it?

**Comment by CamielBouchier** [comment]
Hi,
Right you are! I did add it again for the last release.
(note you can obtain it now also through the thunderbird-add-on functionality. Should document that part still ...)
Camiel B.

**Comment by BenjaminKobjolke** [comment]
Thanks!
