### ISSUE TITLE
Mail toolbar icon not working in Thunderbird 91.7.0 64-bit

### ISSUE THREAD

**Issue by JohnAnderson** [CamielBouchier/cb_thunderlink#42]
I use cb_thunderlink all the time, so thank you for developing it.  However, the icon that appears on the Mail Toolbar: 
![image](https://user-images.githubusercontent.com/4228382/158840989-ed7a358a-d52c-4b5c-a8cb-b552c1df75e5.png)
doesn't do anything when you click it.  The only way I'm able to run the addon is by right-clicking the message in the message-list pane.  It would be great if it would run when you click the icon (which appears on the toolbar even when reading a message in another tab where the message list isn't visible).  Is there some way to make that happen?

**Comment by CamielBouchier** [comment]
Hi,

I think you misinterpret the function of this button.
Have a look at https://camiel.bouchier.be/en/cb_thunderlink/architecture/arch.jpg where I try to describe the architecture.

The button is meant for someone who wants to work without the OS integration (lacking e.g. on MacOs, or maybe avoided for security reasons). Without OS integration the button takes the (cb)thunderlink that is in the clipboard and opens the associated the message. It's not meant for getting the link.

Camiel B.
