### ISSUE TITLE
placeholder for 'current' timestamp

### ISSUE THREAD

**Issue by gour** [CamielBouchier/cb_thunderlink#43]
Hello,

I'm glade seeing that https://github.com/CamielBouchier/cb_thunderlink/pull/38 is merged and wonder how difficult would it be to add current timestamp (y-m-d hh.mm:ss) when the link for the task is created?

I've some task where it is very important to notice the correct time when I read the email and create an appropriate task for it.

The same thing I was able to accomplish with Claws-mail and Etm, but this feature would enable me to fully switch/use TB. 

Sincerely,
Gour

**Comment by CamielBouchier** [comment]
Hi,

That should be rather straightforward. I'd probably have to define a setting for the timeformat as well.
As usual: if and when I find some time to add/test/package I'll do. 

Camiel B.

**Comment by gour** [comment]
Hello,

> That should be rather straightforward. I'd probably have to define a setting for the timeformat as well. 

Yes, please!

> As usual: if and when I find some time to add/test/package I'll do.

Thank you.

I did [integration](https://claws-mail.org/faq/index.php/Using_Claws_Mail_with_other_programs#Integrating_Claws-mail_with_Taskwarrior) between Claws-mail and Taskwarrior, now have between Claws and [Etm](https://github.com/dagraham/etm-dgraham), but this would enable me to fully use Thunderbird which is now used for calendars/contacts, as IRC & Matrix client... :innocent:

**Comment by CamielBouchier** [comment]
Implemented as https://github.com/CamielBouchier/cb_thunderlink/releases/tag/Release_1_4_0
