### ISSUE TITLE
Windows 11 Installation 

### ISSUE THREAD

**Issue by hamby** [CamielBouchier/cb_thunderlink#44]
Hello Camiel Bouchier,
thanks for your work and keeping thunderlink alive! :-)

On Windows 11 i followed this instruction https://github.com/CamielBouchier/cb_thunderlink/blob/main/documentation/50_cb_thunderlink/2_installation/1_windows/en.md

There ist an short CMD Popup, but the mail within thunderbird (91.7.0 (64-Bit)) didn't show up. 

Best Christian

**Comment by CamielBouchier** [comment]
Hi,

I have no access to Windows 11 ... Making it quite difficult to assess what could be going on.
In any case, can you carefully read and follow: https://camiel.bouchier.be/en/cb_thunderlink/checklist

Based on that one, I could maybe have an idea what is going on.

Camiel B.

**Comment by hamby** [comment]
Hello Camiel,
thanks your reply. I tried the checklist under Windows 10, but i couldn't get the link functionality run. But the copy & paste works. That is for me enough and wouldn't investigate further.  
I gonna close this issue.
Thanks a lot for this development.
Best Chris
