### ISSUE TITLE
Using cb_thunderlink on two computers

### ISSUE THREAD

**Issue by bepolymathe** [CamielBouchier/cb_thunderlink#45]
[not realy an issue] 

Good evening, 

I would like to thank you for this tool that you have made available and that I have been using with great pleasure for almost two years. My work organization is going to change with more telecommuting, and therefore two computers. One at home under linux. Another at work on windows. 
Is there any hope that I can use the same links on both machines?
Thanks in advance. 
Have a nice evening.

**Comment by CamielBouchier** [comment]
Hi,

The thunderlink works on the basis of the message-id. Assuming you sync on your 2 machines the same mailbox (e.g. imap mailbox), the message-id is maintained over both. So it should (tm) work ...

Camiel B.
