### ISSUE TITLE
OS integration

### ISSUE THREAD

**Issue by akastrin** [CamielBouchier/cb_thunderlink#46]
I have a question about OS integration. When I run/open Thunderbird myself, the script works perfectly (i.e., it finds the appropriate message). However, when Thunderbird is not running and I run the script in the terminal, I get the following error message:

```
➜  ./cb_thunderlink thunderlink://messageid=lvwozo98VTyJZfYrA6yI4h...
Traceback (most recent call last):
  File "cb_thunderlink.py", line 211, in <module>
ConnectionRefusedError: [Errno 111] Connection refused
[4111] Failed to execute script 'cb_thunderlink' due to unhandled exception!
```
I have also tried the `xdg-open` command, which gives the similar output:
```
➜  xdg-open thunderlink://messageid=lvwozo98VTyJZfYrA6yI4h...
Traceback (most recent call last):
  File "cb_thunderlink.py", line 211, in <module>
ConnectionRefusedError: [Errno 111] Connection refused
[5967] Failed to execute script 'cb_thunderlink' due to unhandled exception!
/usr/bin/xdg-open: line 881: x-www-browser: command not found
/usr/bin/xdg-open: line 881: firefox: command not found
...
/usr/bin/xdg-open: line 881: w3m: command not found
xdg-open: no method available for opening 'thunderlink://messageid=lvwozo98VTyJZfYrA6yI4hCJAnZGqkugh4B5dZ2j0@1ka.arnes.si'
```
Let me know if this is expected or should I start Thunderbird before I call `cb_thunderlink`?

OS info: Arch Linux + Thunderbird 91.9.1 installed through package manager (pacman).

**Comment by CamielBouchier** [comment]
Hi,

It is expected behavior. You should start Thunderbird prior to the call.

I guess it would be technically possible to ensure thunderbird is started before. However that would be heavily OS/distribution dependent, it would be complicated by the use of multiple profiles etc. And thus difficult to maintain.

Compared to that, starting it yourself seems a minor issue.

Camiel B.
