### ISSUE TITLE
Update for Thunderbird >91

### ISSUE THREAD

**Issue by dochego** [CamielBouchier/cb_thunderlink#47]
Thunderbird 102 has been released, but cb_thunderlink is not compatible.
It seems to work by setting strict_max_version to 102.* in manifest.json in the xpi. 
Could this please be updated in a new version.
Thanks!

**Comment by CamielBouchier** [comment]
I dropped a quick release assuming all keeps working in thunderbird 102. 
(which is very likely, there are simplifications possible, but that's for later as I take some time off now)
Camiel B.
