### ISSUE TITLE
Can't copy from the email/conversation tab ?

### ISSUE THREAD

**Issue by tobiasBora** [CamielBouchier/cb_thunderlink#48]
First, thanks for this great addon. It works great if I copy the link from the main page (the one that lists all emails) but if I click on an email to read it (or if I search for it and click on it) it does not work anymore (clicking would just leave the content of the clipboard unchanged).

![image](https://user-images.githubusercontent.com/2164118/189624433-5ab4e668-05b1-4a5a-8955-50178ea71572.png)

I don't know if this can be a problem but I'm using the conversation extension.

**Comment by CamielBouchier** [comment]
Hi,

I am not sure to understand your sequence and issue exactly.  I tried several variations and it seems to work? Yes, an additional extension always can interfere, but frankly spoken,  I don't expect. The cb_thunderlink doesn't contain too much magic after all ...

Camiel B.
