### ISSUE TITLE
Usage guidance missing

### ISSUE THREAD

**Issue by velle** [CamielBouchier/cb_thunderlink#49]
As far as I can tell, there is not information at all about how to use the cb_thunderlink add on. Am I right?

I am new to both Thunderbird and Thunderlink. I found the README for the original Thunderlink, which says that I can right click an email and select Thunderlink, however no such item is there now with cb_thunderlink installed. 

I suspect that by clicking the cb_thunderlink button, it should create a link and copy it to clipboard. But I could be entirely wrong? :) In any case, nothing is copied to clipboard and I cant see that anything happens when I click this button

So how do I use it? :)

Details: Thunderbird 102.2.2 on Ubuntu 22.04.

**Comment by CamielBouchier** [comment]
Hi,

I am not sure what is your starting point of usage but there are 2 "natural" starting points:

* https://addons.thunderbird.net/en-us/thunderbird/addon/cb_thunderlink/
* https://github.com/CamielBouchier/cb_thunderlink

Both refer to https://github.com/CamielBouchier/cb_thunderlink for documentation, which I believe is pretty complet.

Camiel B

**Comment by velle** [comment]
Thank you for your answer. I was under a lot of pressure when I wrote this issue. Somehow missed the tags/links in the menu on the left while reading on https://camiel.bouchier.be/en/cb_thunderlink, and I though that there was only that one page.
