### ISSUE TITLE
cb_thunderlink button does nothing

### ISSUE THREAD

**Issue by velle** [CamielBouchier/cb_thunderlink#51]
When I click the button, nothing happens; also no error or warning. 

![image](https://user-images.githubusercontent.com/4488298/201741827-d622a302-3313-4b0e-8c05-901b935c578a.png)

If I run Thunderbird from console and click the button the following error is printed to console:

    JavaScript error: moz-extension://a99650c3-9fd9-44f7-b515-bffeca93534e/cb_background.js, line 367: TypeError: match is null

It seems to work perfectly when it comes to copying the URIs to clipboard by right clicking an email, and clicking cb_thunderlink and choosing any of the two URI options. 

### Setup/version details:

I installed cb_thunderlink v. 1.6.0 using the Thunderbird tool for searching and installing Add-ons. I tried removing and reinstalling, and the result is the same. 

I also have the Owl add-on installed, but it makes no difference when I disable it. 

I'm on Ubuntu 22.04.1 LTS, with Thunderbird 102.2.2 (64-bit) installed via apt from default repositories.

**Comment by velle** [comment]
Whoooaaa... Sigh. I just realized how I am supposed to use it. The button will use the URI which is in clipboard :)

So copy a URI to clipboard, click the cb_thunderlink button, and it will you to the email identified by the URI.




I'm sorry if it seems that I did not spend enough time before posting. In fact I really did try carefully with enabling/disabling/reinstalling Add-ons, and I tried googling various things, and I read all the documentation once more before posting. But one minute after posting I found the answer ... :)

**Comment by CamielBouchier** [comment]
Hi, yes, this is exactly the expected behaviour.
(the button is there for copying from the clipboard into thunderbird)

Alternatively, you can use the os-integration which would enable you to click links (e.g. in a wiki) that opens the associated mail. In that case the button is useless.

Camiel B.
