### ISSUE TITLE
Confused about installation process for Windows

### ISSUE THREAD

**Issue by pm64** [CamielBouchier/cb_thunderlink#52]
I'm unable to use the "Clickable - OS-integration" feature in Windows:

![image](https://user-images.githubusercontent.com/10715458/217067117-66e4c72d-0bab-47aa-9458-c2a98ce62693.png)

But it's not clear to me that I installed the extension correctly.

After searching for the extension in Add-on Manager and installing it, I noticed the description said "Note that the full os-integration requires the installation of an accompanying program".

I followed the link, and as far as I could tell, the "accompanying program" is cb_thunderlink.exe from cb_thunderlink_windows.zip on this project's GitHub release page. But running that program while using the add-on doesn't affect Windows link handling.

Then I noticed that part in the documentation that says the accompanying program is "started automatically by the add-on". But the plugin has no setting to indicate where cb_thunderlink.exe resides.

So cb_thunderlink.exe must actually ship with the add-on, right? Meaning the accompanying program was present all along, and the whole Github part of this journey wasn't necessary? And perhaps my issue has to do with some incompatibility with newer versions of Windows?

I'm so confused, any guidance would be immensely appreciated.

**Comment by CamielBouchier** [comment]
Hi,

Not sure to understand fully your problem. I tried to document to the best of my knowledge.
Here for windows: https://camiel.bouchier.be/en/cb_thunderlink/installation/windows

If you want to understand how the different components work together: 
https://camiel.bouchier.be/en/cb_thunderlink/architecture

Let me know if something is still not working or unclear after having read those pieces of info carefully.

Camiel B.

**Comment by pm64** [comment]
Please accept my apologies @CamielBouchier, somehow I completely missed that page. The instructions are indeed clear, and after restarting Thunderbird, links are processed as expected. Thanks for your reply and for making this plugin available.

**Comment by CamielBouchier** [comment]
@pm64: no worries, glad I could help so fast. Will close this issue.
