### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bepolymathe** [CamielBouchier/cb_thunderlink#53]
Hi @CamielBouchier 

I have just installed a new machine with thunderbird under linux (Fedora) and I would like to reinstall cb_thunderlink that I have used for several years but I have a problem. 

![image](https://user-images.githubusercontent.com/29939805/220308274-99112bbd-ae51-4636-b21f-5040927844ac.png)

Ok

![image](https://user-images.githubusercontent.com/29939805/220308425-b349af2d-eb60-4f47-95c9-faa5650af1fa.png)

Ok, it works

> Is global indexing enabled?

Yes 

> Consol

![image](https://user-images.githubusercontent.com/29939805/220309193-d515f318-aeca-425f-bde5-09a556490820.png)

Seems to work. 

However I can't get any active links on the whole system. And last thing it's a flatpak 🤔... same problem as snap ?

**Comment by bepolymathe** [comment]
Well I finally installed thunderbird by rpm and it works  👍🏼 

Sorry for the inconvenience

**Comment by CamielBouchier** [comment]
Hi,

Many thanks for your report. I indeed figured out meanwhile that native messaging doesn't work on flatpak either (as it doesn't on snap). Nothing much I can do about it other than updating the documentation, which I did meanwhile.

Indeed, an rpm/deb install should work though.

Camiel B.

**Comment by bepolymathe** [comment]
The documentation was clear, no worries. Thanks for this great tool.
