### ISSUE TITLE
no thunderlink line in context menu, linking also does not work

### ISSUE THREAD

**Issue by Olifair** [CamielBouchier/cb_thunderlink#54]
Hello, I was just soooo happy to discover that thunderlink has been rewritten for newer TB versions. 

I installed in windows 10 following instructions (first installing the plugin, then registering with the external program, then deinstallgin and reinstalling the plugin). Looking at the the log file, all seems fine.
I have restarted TB after installation, just to be sure. 
However I do not see the context menu point Thunderbird when right-clicking on an email.
I also have tried my old thunderlink links, I see a command window flashing and then nothing happens. I see in the logfile : 
_2023-03-03 15:34:19,676 - 22776 - INFO -   86 : Starting cb_thunderlink (['C:\\Users\\myname\\cbThunderlink\\cb_thunderlink.exe', 'thunderlink://messageid=f4d2bda7-70fb-4d15-2d88-7fc9a5ee8ac4@domain.fr/'])
2023-03-03 15:34:19,676 - 22776 - INFO -  209 : Executing cb_thunderlink
2023-03-03 15:35:45,939 - 16208 - INFO -   85 :_

  If I search for the message-ID manually, I do still find the email. 

Any ideas ? 

I'm using TB 102.8.0 (32 bits)  on a windows 10 pro 64 bits

Oliver

**Comment by CamielBouchier** [comment]
YW :)
