### ISSUE TITLE
no link created in Thunderbird 115

### ISSUE THREAD

**Issue by sfischme** [CamielBouchier/cb_thunderlink#58]
The context menu to create a thunderlink doesn't work. It creates no link under linux. Neither posts something to the clipboard or the Xorg selection.

Also the context menu doesn't have a proper description, it just says "cb_thunderlink", so I don't think it's properly working under Thunderbird 115 yet.

![2023-07-23-213008_6000x1440_scrot](https://github.com/CamielBouchier/cb_thunderlink/assets/250263/2b3c3fd5-be60-4921-aa9a-82e4005b2d78)

It might be useful to add an option to display the thunderlink in a dialog so one can copy&paste it.

**Comment by sfischme** [comment]
Btw. Ctrl+Alt+1 and other shortcuts are working, so generating a thunderlink and copying to the clipboard is working.

**Comment by baerbel2019** [comment]
Same problem with cb_thunderlink 1.7.1 on TB 115.0.1 running on macOS Ventura 13.4.1 on Apple M2 CPU

1. The context menu "cb_thunderlink" has no submenu. Clicking it copied nothing to the clipboard
2. Pressing Command-Option-1 copies the cb_thunderlink to the clipboard

and unfortunately:

3. when trying to use the cb_thunderlink (eg. in firefox) you get the following in the Thunderbird "Multiprocess Browser Console":

```
handle_incoming_link cbthunderlink://MjAyMy0wNy0yNFQxMDoyNTozNS4wMDBaOyJBbmV0dGUgTy4iIDxhbm92ZXJsYWNrQGdvb2dsZW1haWwuY29tPg== [cb_background.js:362:13](moz-extension://ad481b07-d1e0-4695-8bce-4eb78c1996c6/cb_background.js)

WebExtensions: cb_show_message_from_api_id 1 three_pane [cb_api.js:50](jar:file:///Users/USERNAME/Library/Thunderbird/Profiles/PROFILENAME/extensions/cb_thunderlink@bouchier.be.xpi!/cb_api.js)

win.gFolderTreeView is undefined [cb_api.js:68](jar:file:///Users/USERNAME/Library/Thunderbird/Profiles/PROFILENAME/extensions/cb_thunderlink@bouchier.be.xpi!/cb_api.js)
    cb_show_message_from_api_id jar:file:///Users/USERNAME/Library/Thunderbird/Profiles/PROFILENAME/extensions/cb_thunderlink@bouchier.be.xpi!/cb_api.js:68
    result resource://gre/modules/ExtensionParent.sys.mjs:1144
    withCallContextData resource://gre/modules/ExtensionParent.sys.mjs:627
    result resource://gre/modules/ExtensionParent.sys.mjs:1143
    withPendingBrowser resource://gre/modules/ExtensionParent.sys.mjs:637
    result resource://gre/modules/ExtensionParent.sys.mjs:1142
    callAndLog resource://gre/modules/ExtensionParent.sys.mjs:1095
    recvAPICall resource://gre/modules/ExtensionParent.sys.mjs:1141
    AsyncFunctionNext self-hosted:852
Uncaught (in promise) Error: An unexpected error occurred
```

**Comment by CamielBouchier** [comment]
Release_1_7_2 is supposed to address this issue.

Camiel B
