### ISSUE TITLE
bug when using open-mode three pane

### ISSUE THREAD

**Issue by sfischme** [CamielBouchier/cb_thunderlink#59]
When using "Three pane" as Open-mode. the following bug appears in the console:

![2023-07-23-215315_1135x296_scrot](https://github.com/CamielBouchier/cb_thunderlink/assets/250263/bfa26fdd-a571-4fc0-b5ec-0f6dc8140b29)

**Comment by sfischme** [comment]
Thunderbird 115
Linux

**Comment by CamielBouchier** [comment]
Release_1_7_2 is supposed to address this issue.

Camiel B
