### ISSUE TITLE
No Link Created, No Flyout Menu

### ISSUE THREAD

**Issue by dstark** [CamielBouchier/cb_thunderlink#60]
I think [this issue](https://github.com/CamielBouchier/cb_thunderlink/issues/58) may have reemerged with Thunderbird 115.1.1 (Windows 11). I'm not getting thunderlinks copied to the clipboard. And when I enable both cb_thunderlink and thunderlink protocols, I still just have the one cb_thunderlink option in the menu—with no flyout to choose between a cb_thunderlink or a thunderlink.

I've tried restarting Thunderbird, disabling and reenabling cb_thunderlink, and uninstalling and reinstalling cb_thunderlink. But nothing seems to restart the link generation and copying to the clipboard.

If I can provide anything further, please feel free to ask.

Thank you so much for your help!

**Comment by dominique-unruh** [comment]
Do you have version 1.7.1 installed or 1.7.2? (See #61.)

**Comment by CamielBouchier** [comment]
@dstark : see also the remark of @dominique-unruh , is this problem really present or was it a case of not having used the last version (which is meanwhile also on thunderbird addons)? 

Can I close?

**Comment by dstark** [comment]
@CamielBouchier, yes, my apologies. I thought I'd responded here, but I guess not. Upgrading to 1.7.2 did resolve the issue—I just hadn't checked here for an additional version and assumed the one in the Thunderbird addons repository was the most current. Thanks so much!

**Comment by CamielBouchier** [comment]
NP. Happy it works. Camiel B.
