### ISSUE TITLE
Thunderbird Addon page provides 1.7.1

### ISSUE THREAD

**Issue by dominique-unruh** [CamielBouchier/cb_thunderlink#61]
https://addons.thunderbird.net/en-us/thunderbird/addon/cb_thunderlink/ still provides version 1.7.1, even though the current version is 1.7.2 since July 28 according to the Github page.

**Comment by CamielBouchier** [comment]
> https://addons.thunderbird.net/en-us/thunderbird/addon/cb_thunderlink/ still provides version 1.7.1, even though the current version is 1.7.2 since July 28 according to the Github page.

Yes, I was expecting feedback whether this works sufficiently or not. But as there's none, let me take a leap of faith and release on the addon page as well.
