### ISSUE TITLE
Links don't start being made until the 'cb_thunderlink' button is pressed.

### ISSUE THREAD

**Issue by Damskibobs** [CamielBouchier/cb_thunderlink#62]
When I first load thunderbird, right clicking on an email and going to 'cb_thunderlink > cbthunderlink' or 'cb_thunderlink > thunderlink' does NOT create a link. No matter how many times I do it.

The only way to 'wake' the system is to press the 'cb_thunderlink' button (which for me is at the top right of the screen, next to the minimise and maximise buttons. After that button is pressed (which I believe is only supposed to be needed for pasting a link back into Thunderbird), then all future links are generated fine. Right click and 'cb_thunderlink > cbthunderlink' or 'cb_thunderlink > thunderlink' both work as expected ...

For a while.

After a relatively short amount of time, this situation repeats itself. Again, links stop generating useless the button is pressed first. Th button seems to wake the system up.

**Comment by CamielBouchier** [comment]
Hey,

That's kinda weird ...

Can you provide some more info on the thunderbird version you are using and the cb_thunderlink version as well?
Any chance there's interaction with other extensions? Any chance to run cb_thunderlink as only extension?

Can you try to run the checklist at https://camiel.bouchier.be/en/cb_thunderlink/checklist on the moment things go wrong?
It might provide the info I'd need.

Regards.

Camiel B.

**Comment by cipherbrain** [comment]
I have the exact same problem, with the same temporary solution (click on the cb_thunderlink button)

Ubuntu 22.04.3 LTS
Thunderbird 115.2.3

**Comment by CamielBouchier** [comment]
@cipherbrain : thanks for the report. If you would have some traces as suggested in https://camiel.bouchier.be/en/cb_thunderlink/checklist , that would be even more helpful.

@Damskibobs : can you complement with your exact environment (OS, TB version)? And maybe also with the traces as suggested in https://camiel.bouchier.be/en/cb_thunderlink/checklist ?

(BTW: I assume you are both using the latest version of cb_thunderlink published here on github)

Probably I'll have some time this weekend to have a look into. I have some hunch about what might be the case ...

Camiel B.

P.S. I myself am still on the 102 TB version (not particularly wild of new UX, incompatible add-ons etc.), so it takes some time to set-up an 115 replica and why I have to rely heavily on your input guys ...

**Comment by Damskibobs** [comment]
I’m on the road for a few days. Will try to help next week.I’m on Windows 10 and latest Thunderbird. DamianOn 27 Sep 2023, at 7:41 am, Camiel B ***@***.***> wrote:﻿
@cipherbrain : thanks for the report. If you would have some traces as suggested in https://camiel.bouchier.be/en/cb_thunderlink/checklist , that would be even more helpful.
@Damskibobs : can you complement with your exact environment (OS, TB version)? And maybe also with the traces as suggested in https://camiel.bouchier.be/en/cb_thunderlink/checklist ?
(BTW: I assume you are both using the latest version of cb_thunderlink published here on github)
Probably I'll have some time this weekend to have a look into. I have some hunch about what might be the case ...
Camiel B.
P.S. I myself am still on the 102 TB version (not particularly wild of new UX, incompatible add-ons etc.), so it takes some time to set-up an 115 replica and why I have to rely heavily on your input guys ...

**Comment by CamielBouchier** [comment]
Can you give me the feedback whether 1.7.3 (released here only on github) does the trick?

**Comment by cipherbrain** [comment]
With the latest version (installed from the xpi downloaded from github), version 1.7.3, latest update "2023-10-02".
Previously generated links still works.
Newly generated links works.
The context item in the context menu works:
generation of links works right at the start (ie: workaround of clicking on the 'cb_thunderlink' button is not needed anymore).

Thanks!

**Comment by dochego** [comment]
For me, pre-1.7.3, in addition to not being able to generate links (using the keyboard shortcuts), thunderlink-links would also not open the message in Thunderbird. My work-around was to disable and re-enable the cb_thunderlink extension in the running Thunderbird.

v1.7.3 from github fixes this issue for me - thanks a lot!
This is one of my must-have extensions.

(Thunderbird 115.3.1 on Linux)

**Comment by CamielBouchier** [comment]
Thanks for the confirmations.

**Comment by Damskibobs** [comment]
Fixed! :-)
Thank you!!
