### ISSUE TITLE
Links not working in Windows

### ISSUE THREAD

**Issue by Damskibobs** [CamielBouchier/cb_thunderlink#63]
When I generate and add a link to my online todo tool, clicking the links doesn't work in Firefox.

Nor does it work if I post the link directly into the Firefox bar.

Nothing seems to happen in Firefox, or Thunderbird.

I can see that an application (cb_thunderlink for windows?) 'pops up', but it goes off screen too quickly to see anything.

I have repeated this with Chromium and Opera. Something pops up, but nothing happens in Thunderbird.

I've installed  cb_thunderlink_windows.zip version 1_7_2.

I'm using Windows 10, Firefox 117.0.1 and Thunderbird 115.2.3

Do you have any idea how to fix this?

Thanks

**Comment by CamielBouchier** [comment]
Hi,

Can you run the checklist at https://camiel.bouchier.be/en/cb_thunderlink/checklist. It might provide the info I'd need to debug this.

Camiel B.

**Comment by CamielBouchier** [comment]
@Damskibobs : not sure if this is still an active issue for the 1.7.3 version?

**Comment by Damskibobs** [comment]
Unfortunately, the OS integration is still not working with version 1.7.3.

I have run through the checklist as far as I can. But, as soon as Error consoles and log files are needed, I'm out of my depth.

Such a shame. This plugin would be really useful for me! I just can't get it to work.

**Comment by CamielBouchier** [comment]
@Damskibobs : unfortunately it's the only way I can give some sensible advice on what might go wrong. The combination is pretty much the one I am using (and likely many others) without any issue.

The only other advice is to restart your computer and do the installation again (carefully reading and following https://camiel.bouchier.be/en/cb_thunderlink/installation/windows)

**Comment by Gluups** [comment]
Hello,
I see a message of a few weeks ago, is Thunderlink still available?

**Comment by CamielBouchier** [comment]
> Hello, I see a message of a few weeks ago, is Thunderlink still available?

It is confusing to read this question in this thread. Don't understand. Anyhow: cb_thunderlink is alive and kicking. 
Camiel B.

**Comment by Gluups** [comment]
OK, thank you and excuse me for the protocol error.
