### ISSUE TITLE
Windows OS Integration is not working for me.

### ISSUE THREAD

**Issue by viking2** [CamielBouchier/cb_thunderlink#65]
I needed to find a new Email program and, apart from Outlook, Thunderbird is the only Email program where I can create hyperlinks to Email messages using your Add-On. Unfortunately I have not been able to get it to work yet :-(.

I have TB v 115.4.3 (32-bit), cb_thunderlink 1.7.3 and Windows 7.
I installed the zip file by "cb_thunderlink.exe register" and then installed the xpi file
I went through the troubleshooting here https://camiel.bouchier.be/en/cb_thunderlink/checklist 
1. I created the thunderlink link using the context-menu and then clicked on the button. That worked fine.
2. I then pasted the link elsewhere as a hyperlink. The link looks like this: 
thunderlink://messageid=462b7c26-8415-4b10-8069-0a7435119458@atl1s07mta2806.xt.local/
3. When I click on this link, it opens a new Outlook message to be sent to the address of the link (I also have Oultook 2010 on this PC)! I guess the registration somehow failed?
4. I can find the message through the 'search messages' option of thunderbird itself.

5. I don't understand what you mean by "Do a cycle of generating a link and pasting it using the button as described earlier." in the "**Check error console**". Where/how should I paste the link?
5. In any case, I started the error console and created a link again, and then clicked the button. 
**Here is the output:**

```
1700542490972	addons.xpi	WARN	Checking C:\Prog_RB\P_Comm\Thunderbird\distribution\extensions for addons
Found 0 public keys and 0 secret keys (0 protected, 0 unprotected) RNPLib.jsm:551:15
services.settings: Failed to load last_modified.json: TypeError: NetworkError when attempting to fetch resource. Utils.sys.mjs:322
1700542492885	addons.xpi	WARN	Addon with ID thunderbird-compact-light@mozilla.org already installed, older version will be disabled
1700542492885	addons.xpi	WARN	Addon with ID thunderbird-compact-dark@mozilla.org already installed, older version will be disabled
cb_background started cb_background.js:14:9
Failed to create process NativeMessaging.sys.mjs:115
NotSupportedError: ClonedErrorHolder constructor: We can only clone DOM Exceptions and native JS Error objects: onConnect/<@resource://gre/modules/NativeMessaging.sys.mjs:140:48
handler@resource://gre/modules/EventEmitter.sys.mjs:91:19
emit@resource://gre/modules/EventEmitter.sys.mjs:154:20
_cleanup@resource://gre/modules/NativeMessaging.sys.mjs:291:12
NativeApp/this.startupPromise<@resource://gre/modules/NativeMessaging.sys.mjs:116:14
EventEmitter.sys.mjs:158
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. 2 aboutMessage.js:54
downloadable font: failed to start download (font-family: "Targetica" style:normal weight:400 stretch:100 src index:0): content blocked source: https://assets.targetimg1.com/ui/fonts/99ecc614-958b-457a-be15-01e00c53057A.woff2 2
downloadable font: failed to start download (font-family: "Targetica" style:normal weight:400 stretch:100 src index:1): content blocked source: https://assets.targetimg1.com/ui/fonts/99ecc614-958b-457a-be15-01e00c53057A.woff 2
downloadable font: failed to start download (font-family: "Targetica" style:normal weight:700 stretch:100 src index:0): content blocked source: https://assets.targetimg1.com/ui/fonts/3420ab8a-6ccf-4c75-9da7-efe26f1cedAA.woff2 2
downloadable font: failed to start download (font-family: "Targetica" style:normal weight:700 stretch:100 src index:1): content blocked source: https://assets.targetimg1.com/ui/fonts/3420ab8a-6ccf-4c75-9da7-efe26f1cedAA.woff 2
Storing in clipboard: thunderlink://messageid=462b7c26-8415-4b10-8069-0a7435119458@atl1s07mta2806.xt.local 2 cb_background.js:258:13
Uncaught (in promise) DOMException: Clipboard write is not allowed.
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. 2 aboutMessage.js:54
handle_incoming_link thunderlink://messageid=462b7c26-8415-4b10-8069-0a7435119458@atl1s07mta2806.xt.local cb_background.js:380:13
WebExtensions: cb_api started cb_api.js:14
WebExtensions: cb_show_message_from_msg_id 115 462b7c26-8415-4b10-8069-0a7435119458@atl1s07mta2806.xt.local three_pane 
Array []
 
Array []
cb_api.js:81
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. 2 aboutMessage.js:54
downloadable font: failed to start download (font-family: "Targetica" style:normal weight:400 stretch:100 src index:0): content blocked source: https://assets.targetimg1.com/ui/fonts/99ecc614-958b-457a-be15-01e00c53057A.woff2 2
downloadable font: failed to start download (font-family: "Targetica" style:normal weight:400 stretch:100 src index:1): content blocked source: https://assets.targetimg1.com/ui/fonts/99ecc614-958b-457a-be15-01e00c53057A.woff 2
downloadable font: failed to start download (font-family: "Targetica" style:normal weight:700 stretch:100 src index:0): content blocked source: https://assets.targetimg1.com/ui/fonts/3420ab8a-6ccf-4c75-9da7-efe26f1cedAA.woff2 2
downloadable font: failed to start download (font-family: "Targetica" style:normal weight:700 stretch:100 src index:1): content blocked source: https://assets.targetimg1.com/ui/fonts/3420ab8a-6ccf-4c75-9da7-efe26f1cedAA.woff 2
mail.activity: OnDownloadError: All Mail of xxxxxxx@gmail.com
autosync.jsm:394:16
```

Thanks in advance!

**EDIT:** I also tried to create a link using cbthunderlink, and I get a link that looks like this:
cbthunderlink://MjAyMy0xMS0yMVQyMjoxNDozOS4wMDBaOyJUYXJnZXQiIDx0YXJnZXRuZXdzQGVtLnRhcmdldC5jb20+
This also works when I click the button, but it is very slow. It takes at least 5 sec before it goes to the message because TB %CPU is maxing out. If I create a hyperlink and click on it, it transiently opens up a DOS window and nothing else happens. (This is in contrast to the thunderlink hyperlink, which opened a new Outloook message...)

p.s. I am currently using TB v115. However, I plan to install v102 instead because of another add-on that doesn't work with v115. I hope that cb_thunderlink will also work with v102?

**Comment by viking2** [comment]
I tried to run it directly from the Admin command prompt and I got an error. Maybe I didn't do it correctly? If I did it correctly, any idea why my target machine actively refused it? 
```
D:\@Prog_RB_Portable\cb_thunderlink>cb_thunderlink.exe "thunderlink://messageid=
HP2v60000018bf98bcb92afc1ebf4bbc786c8225@em.autozone.com"
Traceback (most recent call last):
  File "cb_thunderlink.py", line 211, in <module>
ConnectionRefusedError: [WinError 10061] No connection could be made because the
 target machine actively refused it
[30836] Failed to execute script 'cb_thunderlink' due to unhandled exception!

D:\@Prog_RB_Portable\cb_thunderlink>
```

**Comment by CamielBouchier** [comment]
Will have a look next Wednesday, enjoying some time off😊

**Comment by viking2** [comment]
> Will have a look next Wednesday, enjoying some time off😊
OK. looking forward to it!
Happy Thanksgiving!

**Comment by CamielBouchier** [comment]
Hmz.

That sounds strange and complicated. I have the feeling you are having a problem in the set-up and that during checking you are adding problems that were not there in the first place.

Let me try to guess and advice:

Running from the command prompt is a good starting point indeed. The "ConnectionRefusedError ... no connection could be made because ..." is likely a red herring. The "port" was in use (by cb_thunderlink), not released and therefore you are stumbling into this one. The most certain way to rule this out is to restart your PC and see if you are *still* encountering. The cases I got this error, it was always resolved this way. Waiting long enough might be ok as well, but less certain.

How the hell clicking a cb_thunderlink does result in opening outlook goes beyond my imagination ... Are you really, really sure that this is the link you are clicking and not some "mailto:" or similar thing? I'd remove all thunderlink references from the registry and start the whole process of registering and installing from in the beginning. It really makes no sense ...

Then there is the error message: 
Failed to create process NativeMessaging.sys.mjs:115
NotSupportedError: ClonedErrorHolder constructor: We can only clone DOM Exceptions and native JS Error objects: onConnect/<@resource://gre/modules/NativeMessaging.sys.mjs:140:48

That is definitely an issue! But I can't find any reference to what might cause it. Might it be the windows 7? No idea ... For sure your Thunderbird version is supported, many are working with it .... Can you restart all from zero? Any chance to reproduce on a Win 10 machine?

Camiel B.

**Comment by stepanholub** [comment]
A similar issue here. I have installed the add-on. The usage through the button works. But when clicking the link nothing happens, and the Error Console contains

Storing in clipboard: thunderlink://messageid=CAE+m_h7LstM482drh5-bKSzEX80itBL_CqAVOVy-RxsgjQK49Q@mail.gmail.com 2 [cb_background.js:258:13](moz-extension://0b283336-8377-47a0-9906-5203188697f1/cb_background.js)
Uncaught (in promise) DOMException: Clipboard write is not allowed.
NotFoundError: No such JSWindowActor 'DevToolsFrame'

**Comment by stepanholub** [comment]
Just restarting the machine yields the same error as before. Should I repeat the installation process in some order?

**Comment by CamielBouchier** [comment]
I would guess that won't help. But where start guessing what might go wrong ...
(you might want to have a look to https://camiel.bouchier.be/en/cb_thunderlink/architecture to "think along").

Stupid question: is thunderbird + the active extension running when you issue the command? It must be running.

Might there be any firewall active that is preventing communication. (Maybe switch off windows defender or equivalent a couple of minutes?)

Camiel B.

**Comment by stepanholub** [comment]
Stopping AVG antivirus does not help.
I observe a strange fact. Although the link is copied to the clipboard, still the TB Error Console issues "Uncaught (in promise) DOMException: Clipboard write is not allowed.". More precisely, there are two lines:

Storing in clipboard: thunderlink://messageid=dd234d22-0a66-4e6a-5190-cd2fe3ff8a9f@pruvisto.org 
2 [cb_background.js:258:13](moz-extension://0b283336-8377-47a0-9906-5203188697f1/cb_background.js)

Uncaught (in promise) DOMException: Clipboard write is not allowed.

(I have to stop for now. Can try more later. Thanks for your assistance.)

**Comment by viking2** [comment]
I was finally able to try it on a WIN10 machine;

I installed an older version portable version of Thunderbird; v102_102.15.1, cb_thunderlink_windows and cb_thunderlink.xpi. It worked! 

**Two questions:**

1. I currently have a script for Outlook that creates links. When I click on such a  link, the actual message opens up. However, with Thunderlink it only selects the message in Thunderbird. Is it possible to instead have the Thunderbird message open up like in Outlook?

2. I will try on my WIN7 machine again using the older portable version. However, how do I remove the previously installed traces of cb_thunderlink_windows? I assume that they are all in the registry?

**Comment by CamielBouchier** [comment]
Concerning 1: You might want to look to the settings. There's the 'open-mode'. "new tab" or "new window" might come close to what you want?

Concerning 2: Yes. But simply registering should overwrite previous settings just like that.

**Comment by viking2** [comment]
1. Yes, "new window" does what I wanted.

2. The older vportable version of Thunderbird; v102_102.15.1 worked fine with cb_thunderlink_windows and cb_thunderlink.xpi on my WIN7 machine!
 I am not sure that it worked because I used an older TB version or because it is the portable version (vs. the regular installed TB v115 - which didn't work with cb_thunderlink_windows)

**Comment by CamielBouchier** [comment]
Concerning 2, I still smell some confusion. There is nothing like an "installed" or a "portable" version. See also carefully documentation.

There's the "xpi" that adds the functionality of getting a thunderlink and triggering the thunderlink through the button added in thunderbird. 

There's an accompanying program that extends such functionality such that your os recognizes links and clicking them triggers them. That same program has to register itself and the link scheme in the OS as well. That accompanying program can be sitting wherever, so it is "portable" in your language. However, whenever you move it, it needs to re-register such that clicking a link can trigger the program.

Camiel B.

**Comment by viking2** [comment]
I was talking about the portable version (v102_102.15.1) Thunderbird: https://portableapps.com/apps/internet/thunderbird-portable-legacy-102 versus the regular installed version of Thunderbird (in my case v115): https://www.thunderbird.net/en-US/. 

cb_thunderlink worked with my Thunderbird portable version (v102_102.15.1) but not my regularly installed version ( v115)

**Comment by CamielBouchier** [comment]
Ah. My mistake!

I can't figure out a reason though to explain the behavior you are seeing ....

Camiel B.
