### ISSUE TITLE
Thunderlink Version 1.7.3 isn't compatible with Thunderbird 128.2.3esr

### ISSUE THREAD

**Issue by hamby** [CamielBouchier/cb_thunderlink#69]
The cb_thunderlink plugin is in Thunderbird 128.2.3esr Version deactivated (after the Upgrade) and there is no opportunity to install it or activate it. Thunderbird says it isn't compartible.

Is there a plan to fix it or is cb_thunderlink out of maintenance

Thanks
Christian

**Comment by CamielBouchier** [comment]
I think if you take the one here from github, install it according to the instructions on https://camiel.bouchier.be/en/cb_thunderlink it should work. It's not accepted though on "thunderbird add-ons" for the moment.

**Comment by hamby** [comment]
Thanks for your quick reply. You are right, it works. Didn't see that there is already version 1.7.4 available.
Thanks

**Comment by CamielBouchier** [comment]
Yw
