### ISSUE TITLE
Doesn't seem to work for certain message types

### ISSUE THREAD

**Issue by lingnand** [CamielBouchier/cb_thunderlink#7]
This has worked great for my email messages (i.e., press the keyboard shortcut I assigned and I get the link copied), but for some reason it doesn't seem to work consistently for my *feed* messages. I know feed message is probably not intended to be used on by this addon (or the precursor), but I had used Thunderlink on them previously to great result.

Conceptually, feed message should just be like normal email message, right? I tested opening links for feed messages - this worked just fine. It's just the capturing part is somehow amiss.

**Comment by CamielBouchier** [comment]
@lingnand: thanks for your feedback.

Actually I do expect it working for feeds indeed. I did a short check at my installation and it seems to work.
Before we dive deeper into the issue, may I suggest you close Thunderbird, go into the profile and remove `global-messages-db.sqlite`. Then you open Thunderbird again and wait "some time". "Some time" depends on the number of mails you have but can easily accumulate into hours. I suggest you waiting until you do not see the `global-messages-db.sqlite` growing in size.
(this is the global database and on one of my accounts the plugin did not work consistently due to incomplete/corrupted gloda)

Camiel B.

**Comment by CamielBouchier** [comment]
@lingnand: I removed my previous message as I simply misread yours. Are you saying that you just can't "cut" the link? Not with the shortcut key, not with the context-menu?

Camiel B.

**Comment by lingnand** [comment]
Yes, that's right. I only tested the shortcut key - the context menu is eerily no where to be found on my Thunderbird (68.12.1), at least not in the same place where normally the old Thunderlink menu entry appears.

I just did a bit more testing today - it appears that the bug only shows up on a 'folder' basis: if a feed message is 'capturable' i.e. pressing the shortcut key does indeed 'cut' the link, then all the rest of the messages in the same folder seem to work fine. But if a message is not 'capturable' i.e., pressing the shortcut key seems to do nothing, all the rest of the messages in the same folder also don't work. I changed my shortcut key assignment a couple times and the problem remains.

**Comment by CamielBouchier** [comment]
Can you try with the context menu as well? 

That is : you select the message, right mouse click and then there should be a context menu allowing you to select `cbthunderlink` or `thunderlink`.

Also, could you run the developer tools and see if any message appears in the console that might shed some light on the issue?

Camiel B.

**Comment by lingnand** [comment]
Ha, apparently is this:

```
nvalidCharacterError: String contains an invalid character      cb_background.js:96
```

That line is:

```
    let cblink  =  btoa(date.toJSON() + ";" + author)
```

I do indeed have some non-ASCII-character-named authors subscribed to - so that's the mystery then! Googling shows this: https://stackoverflow.com/a/45725439

**Comment by CamielBouchier** [comment]
@lingnand 
Could you give a try to the xpi in the zip hereto attached?
If it works for you I will generate an updated release later today or tomorrow.

[cb_thunderlink.zip](https://github.com/CamielBouchier/cb_thunderlink/files/5397911/cb_thunderlink.zip)

**Comment by lingnand** [comment]
This seems to have done the job! Thanks for the quick response!
