### ISSUE TITLE
Building the extension

### ISSUE THREAD

**Issue by lingnand** [CamielBouchier/cb_thunderlink#8]
This might just be my own unfamiliarity with 7z, but... I tried your `build.sh` and it didn't yield a useful xpi. I see there is a `@files_in_xpi.lst` referenced in the script - where is this list coming from?

**Comment by CamielBouchier** [comment]
@lingnand what is exactly the issue? `files_in_xpi.lst` should be in the `mail_extension` directory. I guess you checked `7z` is installed on your system (and part of the path)?

**Comment by lingnand** [comment]
You're right, I'm not sure how I missed that; the `xpi` is being made correctly :)
